### ISSUE TITLE
Currency conversion returns NaN

### ISSUE THREAD

**Issue by mushroom-disaster** [r-anime/misato#183]
When using incorrect currency codes the command returns NaN. We need to check if the code is valid before attempting to convert it.

**Comment by AlfredoVillegas** [comment]
hello, in this pull request I added unit validation for the use case of converting currency.
if the units received are not accepted, it throws an error.

https://github.com/r-anime/misato/pull/184

**Comment by eritbh** [comment]
Fixed in #184
